### ISSUE TITLE
Images are not visible on Internet Explorer 11

### ISSUE THREAD

**Issue by hzhu** [zendeskgarden/website#282]
## Expectations

Images should be visible on Internet Explorer 11.

## Reality

Images are not visible on Internet Explorer 11.

<img width="2557" alt="Screen Shot 2021-06-15 at 12 35 23 PM" src="https://user-images.githubusercontent.com/1811365/122113245-af240180-cdd6-11eb-90a5-332a0b41fe28.png">

## Steps to Reproduce

1. Open Internet Explorer 11
1. Navigate to https://garden.zendesk.com/
1. Notice the images do not show up

### Fine Print

- URL: https://garden.zendesk.com/
- Version: N/A
- Browsers: IE11

**Comment by jzempel** [comment]
From `gatsby-image`...

> `gatsby-image` is now backed by the newer `<picture>` tag. This newer standard allows for media types to be chosen by the browser without using JavaScript. It also is backward compatible to older browsers (IE 11, etc).

In fact, IE11 [does not support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#browser_compatibility) the `<picture>` tag. But I don't think we need to be concerned about this for the website. I'd recommend closing this as no-plans-to-fix.
