### ISSUE TITLE
Failed to clone git@github.com:zendeskgarden/react-components.git

### ISSUE THREAD

**Issue by asc2683** [zendeskgarden/website#334]
## Expectations

Successful installation of dependencies. 

## Reality

Get the following error message:
`
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:zendeskgarden/react-components.git' into submodule path '/Users/code/Temp/website/react-components' failed
Failed to clone 'react-components' a second time, aborting
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

## Steps to Reproduce

1. Download repository and cd into website
2. Run yarn install

### Fine Print

- URL:
- Version:
- Browsers: all

**Comment by jzempel** [comment]
The code is fully open source. But you would need Zendesk-internal permissions to perform the install/build.
