### ISSUE TITLE
Figma REST API returning 400 error

### ISSUE THREAD

**Issue by geotrev** [zendeskgarden/website#580]
## Overview

Garden extracts assets from a Figma file to populate images across several pages. This is primarily through the use of two APIs, the [files](https://www.figma.com/developers/api#get-files-endpoint) and [images](https://www.figma.com/developers/api#get-images-endpoint) endpoints.

We generalize the API call using a [function utility](https://github.com/zendeskgarden/website/blob/main/plugins/gatsby-source-garden-content/utils.ts#L58). Garden then hits the `files` and `images` endpoints during the build, first by getting the [frame node IDs](https://github.com/zendeskgarden/website/blob/main/content/figma/assets.yml), [here](https://github.com/zendeskgarden/website/blob/main/plugins/gatsby-source-garden-content/utils.ts#L98) (files) and [here](https://github.com/zendeskgarden/website/blob/main/plugins/gatsby-source-garden-content/utils.ts#L117) (images), respectively.

## Expectations

The endpoints consistently return the associated file/image assets within the 55 second timeout allowed by the REST API, as they have been for the past year.

## Reality

The API has suddenly began returning 400 errors. This happened before, about a week ago, and the "answer" at the time appeared to be deleting and recreating frames within our assets Figma file. I assume the same issue is continuing here.

To be clear, it _appears_ that specific frames are buggy/erroneous, delaying the API call and resulting an error state. Previously, each of the API calls would take ~20 seconds each, well within the timeout.

## Steps to Reproduce

1. Clone the repo and install the dependencies (`npm i`). You should be on `main`.
2. The build should run as a `postinstall` script – you'll see this Figma 400 error:
    <img width="590" alt="Screenshot 2024-04-30 at 3 04 06 PM" src="https://github.com/zendeskgarden/website/assets/3946669/ce4f458f-7465-4a8d-aac0-cf6282ec7135">

To make the build "work" (and test that this is a Figma issue):

1. Run `rm -rf public .cache` to clear build artifacts.
2. Delete the folder `src/pages/patterns` and delete all [asset entries](https://github.com/zendeskgarden/website/blob/main/content/figma/assets.yml) whose node name begins with `patterns-`.
3. Run `npm run build` and notice the build passes without errors.

### Fine Print

- URL: `https://api.figma.com/v1/images/HifWgSrdeTlMMXUrcnrAAH?ids=*`
- Version: Latest
- Environment: Node / Figma API

**Comment by geotrev** [comment]
It appears this bug is being tracked publicly on one of Figma's repos [here](https://github.com/figma/figma-api-demo/issues/46).

**Comment by leffsu** [comment]
> It appears this bug is being tracked publicly on one of Figma's repos [here](https://github.com/figma/figma-api-demo/issues/46).

Hi! That one is for files, not images. The solution could be similar though

**Comment by geotrev** [comment]
@leffsu that's correct - we're seeing the same issue but on images is all. :)
